# Generated by Django 5.2.4 on 2025-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель'), ('admin', 'администратор')], default='buyer', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
