# Generated by Django 5.2.4 on 2025-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('shop', 'Магазин'), ('employee', 'Работник магазина'), ('buyer', 'Покупатель')], default='buyer', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
